#!/usr/bin/expect -f
set timeout 15
#set username [lindex $argv 0]
#set password [lindex $argv 1]
#set hostname [lindex $argv 2]
#log_user 0
spawn passenger-install-apache2-module
send_user "passenger is being installed - this takes a while"
expect "*"
expect "*Press Enter to continue, or Ctrl-C to abort.\n$"
send -- "\r"
expect "*"
expect "*Meteor$"
send -- "\r"
expect "*"
expect "*Press ENTER to continue.\n$"
send -- "\r"
expect "*"
expect eof
#interact

